# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stl < Formula
  desc "The official CLI for stainless."
  homepage "https://stainless.com"
  version "0.1.0-alpha.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.14/stl_0.1.0-alpha.14_macos_amd64.zip"
      sha256 "9fe7cb882e4d586e8bb17deadab031bc2718f6d2137bf7d8eb1b22e35e61757e"

      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.14/stl_0.1.0-alpha.14_macos_arm64.zip"
      sha256 "812bdcb92bcfb6e036f578a671c1eaf06f6d328360d0ea15c6d10b959b6a525e"

      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.14/stl_0.1.0-alpha.14_linux_amd64.tar.gz"
      sha256 "48b5cb3303eab95d39eb047e9fe91b1cc5177cd11f0fc8bc57e7a3956442804b"
      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.14/stl_0.1.0-alpha.14_linux_armv6.tar.gz"
      sha256 "5188b2e519c9f072a81a6fbedfe6e7b1774fe09f167c82c0873657367e6929bb"
      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.14/stl_0.1.0-alpha.14_linux_arm64.tar.gz"
      sha256 "421fcda81b134d46bb1ed7333ea594fa977d1939a08565822c384404c940e05d"
      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
  end
end
