# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stl < Formula
  desc "The official CLI for stainless."
  homepage "https://stainless.com"
  version "0.1.0-alpha.21"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.21/stl_0.1.0-alpha.21_macos_amd64.zip"
      sha256 "eeeca66cda3c4c768e142d2eff1b5f25c389aff0603e6e43ee144a01d043d2bb"

      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.21/stl_0.1.0-alpha.21_macos_arm64.zip"
      sha256 "1b4d80feb8f332c61f1fcdd312c9e5170176d585c2c03328c71e74eadabcc5d5"

      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.21/stl_0.1.0-alpha.21_linux_amd64.tar.gz"
      sha256 "68967811394013887d50296dfd93a649867eb131a20ba7adb6358e4e0cc5a7aa"
      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.21/stl_0.1.0-alpha.21_linux_armv6.tar.gz"
      sha256 "aa60b2bbc38635aa1b8c768318a2c229782f39d8557b0aed7f9b1308d9f31221"
      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v0.1.0-alpha.21/stl_0.1.0-alpha.21_linux_arm64.tar.gz"
      sha256 "3d1c34bcb2fd4f7623e7a3f566b795befcefbb8b915b99a8fe6f138f50e1df2f"
      def install
        bin.install "stl"
        bash_completion.install "completions/stl.bash" => "stl"
        zsh_completion.install "completions/stl.zsh" => "_stl"
        fish_completion.install "completions/stl.fish"
      end
    end
  end
end
