# This file was generated by GoReleaser. DO NOT EDIT.
cask "stl" do
  version "0.1.0-alpha.87"

  on_macos do
    on_intel do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_macos_amd64.zip"
      sha256 "1ed2b937783ff547aafd8fe3eb0f823832e581cba36b676521968fdd9d752f0b"
    end
    on_arm do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_macos_arm64.zip"
      sha256 "258cc95f50d769d7d69adcd909f525b077750a9952bc52ba9db14fd1974fb9f6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_linux_amd64.tar.gz"
      sha256 "459b0951b5b192f04a96dfb5e38ac934e7be76faa61516d090b0e2b1e217f50a"
    end
    on_arm do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_linux_arm64.tar.gz"
      sha256 "4e6f5ea2b10d3dd55450ddc95180b72551d9b3cda4166fbd146adf510d705052"
    end
  end

  name "stl"
  desc "The official CLI for stainless."
  homepage "https://stainless.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stl"
  manpage "man/man1/stl.1.gz"
  bash_completion "completions/stl.bash"
  fish_completion "completions/stl.fish"
  zsh_completion "completions/stl.zsh"

  # No zap stanza required

end
