# This file was generated by GoReleaser. DO NOT EDIT.
cask "stl" do
  name "stl"
  desc "The official CLI for stainless."
  homepage "https://stainless.com"
  version "0.1.0-alpha.43"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stl"
  manpage "man/man1/stl.1.gz"
  bash_completion "completions/stl.bash"
  zsh_completion "completions/stl.zsh"
  fish_completion "completions/stl.fish"

  on_macos do
    on_intel do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_macos_amd64.zip"
      sha256 "7759a3a799ac8bddc1bb7dde88dd3974f2423a4930b003bad212dec80e85ab04"
    end
    on_arm do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_macos_arm64.zip"
      sha256 "ad42753ec4a3ac5fe9b3f9119006ec9075631290db3fac4d31f45ab526661d7b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_linux_amd64.tar.gz"
      sha256 "0a47de1acfc748da0f2a6fcb24e0cba4e1725f0159debd1c09c2593896fcb383"
    end
    on_arm do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_linux_arm64.tar.gz"
      sha256 "4b20bd72dc2780bb8de097a579a01dfa1d4fb6d2a0803ca58588b2c4c90a1150"
    end
  end

  # No zap stanza required
end
