# This file was generated by GoReleaser. DO NOT EDIT.
cask "stl" do
  name "stl"
  desc "The official CLI for stainless."
  homepage "https://stainless.com"
  version "0.1.0-alpha.56"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stl"
  manpage "man/man1/stl.1.gz"
  bash_completion "completions/stl.bash"
  zsh_completion "completions/stl.zsh"
  fish_completion "completions/stl.fish"

  on_macos do
    on_intel do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_macos_amd64.zip"
      sha256 "1766c752478ff00f18d75bbffb851757a63cbb23be94d5bf65427f1b92b3eced"
    end
    on_arm do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_macos_arm64.zip"
      sha256 "947b2c889d62898b93133f1fbbe50af3edf43249e70304684a84d939b7b2695a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_linux_amd64.tar.gz"
      sha256 "0ff89ec3aad76f8d7f910a860a952511cb6157c0b933e85f886f5a05d8902801"
    end
    on_arm do
      url "https://github.com/stainless-api/stainless-api-cli/releases/download/v#{version}/stl_#{version}_linux_arm64.tar.gz"
      sha256 "cf32865fbb31b71477bfb3f0b6b37bfacfc3f9cec7b05376aca65a8e2c52af92"
    end
  end

  # No zap stanza required
end
